### ISSUE TITLE
Migrate images into a format that is easier for collaboration

### ISSUE THREAD

**Issue by adrianhopebailie** [mojaloop/mojaloop-specification#10]
The specification contain a rich set of extremely valuable diagrams. 

We should find a way to store these in Git so that it is possible for change requests to be made that include modified versions of the diagrams to illustrate the changes more effectively.

This would require that they are stored in a form that is editable, preferably with minimal extra tooling.

Perhaps SVG is a good option?

**Comment by millerabel** [comment]
Hi Adrian, the Mojaloop community has been using SVG for hand-drawn diagrams and we use PlantUML for sequence diagrams. Both of these formats are text-based and compatible with a Git toolchain. PlantUML in particular is excellent as a high-level actor-process-sequence markup. We use GitHub Flavored Markdown (GFM) for all narrative documents. And we have a simple toolchain that can produce static PDFs from these source files, nicely formatted, for offline reading or printing. I expect the configuration of these tools would work largely as-is for the API specification, with stylistic templates provided by the CCB to their requirements.

Have a look at the documentation files within the Mojaloop repos.

Separately, Kim Walters is exploring the use of hosted Gitbooks to improve the publication quality and provide simultaneous publication in both Web and PDF formats for Mojaloop.io. No change to the source files, just the tool chain.

**Comment by MichaelJBRichards** [comment]
It's worth noting that there seems to be an evolving (though I think as yet undefined) language for sequence diagram markup. For instance, if you strip the enclosing tags (@startuml/@enduml) from a PlantUml description it renders correctly in SequenceDiagram.org. Not sure if this is true throughout the PlantUml spec, but it certainly worked for the E2E sequence diagram. I'll look into this further.

**Comment by ehenrka** [comment]
I did some initial tests and it seems easier out-of-the-box to make more professional-looking diagrams in SequenceDiagram.org than in PlantUML. Below is an example using SequenceDiagram.org to draw Figure 22 in API Definition (also fixed some small issues with the current version, e.g. Payer in current version should be Payer (Agent) for clarity).

![figure 22](https://user-images.githubusercontent.com/30468528/59434876-ab76d200-8dec-11e9-8d8a-7b8a954ec706.png)

The sequence "code" that I used in SequenceDiagram.org:
[figure 22 in API Definition.txt](https://github.com/mojaloop/mojaloop-specification/files/3286167/figure.22.in.API.Definition.txt)

**Comment by ehenrka** [comment]
Please find some minor corrections (some styling, correct font, and an activation which should have stopped earlier) in the below source file and generated image.

[figure 22 in API Definition (minor update).txt](https://github.com/mojaloop/mojaloop-specification/files/3300466/figure.22.in.API.Definition.minor.update.txt)

![figure 22](https://user-images.githubusercontent.com/30468528/59664708-d62ca600-91b1-11e9-91d3-5aad34b1eefa.png)

**Comment by ehenrka** [comment]
Almost the same file could also be used in PlantUML as indicated earlier by @MichaelJBRichards, with some changes in the header of the file using some `skinparam` settings to set up a reasonably good looking diagram.

[figure 22 - plantuml.txt](https://github.com/mojaloop/mojaloop-specification/files/3301319/figure.22.-.plantuml.txt)

![Figure22](https://user-images.githubusercontent.com/30468528/59679317-c5d6f400-91ce-11e9-9366-48e0160a1aa4.png)

**Comment by elnyry** [comment]
Thanks Henrik for this. Let me try it out as well.

**Comment by ehenrka** [comment]
@elnyry Here are some additional `skinparam` settings to make it look more like existing diagrams:
skinparam shadowing false
skinparam defaultFontName Calibri
skinparam monochrome true
skinparam SequenceLifeLineBackgroundColor WhiteSmoke
skinparam SequenceLifeLineBorderColor Black
skinparam ActorFontStyle Bold
skinparam ActorFontSize 20
skinparam ParticipantFontStyle Bold
skinparam ParticipantFontSize 20
skinparam ParticipantBackgroundColor WhiteSmoke

Please note that the `defaultFontName Calibri` does not seem to work on online plantuml, only works locally for me.

**Comment by adrianhopebailie** [comment]
FYI, I got the same code to work with a few modifications in Mermaid
[View live editor here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5QYXllZU90Yy0-PlBheWVyOkkgd291bGQgbGlrZSB0byBDYXNoLUluIHNvXFxudGhhdCBJIHJlY2VpdmUgMTAwIFVTRFxuUGF5ZXItPj5QYXllZU90YzpPSywgeW91IHdpbGwgcmVjZWl2ZSBhIG5vdGlmaWNhdGlvbiBmcm9tXFxueW91ciBGU1AgZGlzcGxheWluZyB0aGUgZmVlc1xuUGF5ZXItPj5QYXllckZTUDpJIHdvdWxkIGxpa2UgUGF5ZWVcXG50byByZWNlaXZlIDEwMCBVU0RcbmFjdGl2YXRlIFBheWVyRlNQXG5QYXllckZTUC0-UGF5ZXJGU1A6IEZlZSBpcyAyIFVTRCBpbiBQYXllciAoQWdlbnQpIEZTUCBmb3IgQ2FzaC1JbixcXG5QYXllciB3aWxsIHJlY2VpdmUgMSBVU0QgaW4gaW50ZXJuYWwgY29tbWlzc2lvblxuUGF5ZXJGU1AtPj5Td2l0Y2g6KipQT1NUIC9xdW90ZXMqKlxcbihhbW91bnRUeXBlPVJFQ0VJVkUsIGFtb3VudD0xMDAgVVNELFxcbmZlZXM9MiBVU0QpXG5hY3RpdmF0ZSBTd2l0Y2hcblN3aXRjaC0tPj5QYXllckZTUDoqKkhUVFAgMjAyKiogKEFjY2VwdGVkKVxuU3dpdGNoLT4-UGF5ZWVGU1A6KipQT1NUIC9xdW90ZXMqKlxcbihhbW91bnRUeXBlPVJFQ0VJVkUsIGFtb3VudD0xMDAgVVNELFxcbmZlZXM9MiBVU0QpXG5hY3RpdmF0ZSBQYXllZUZTUFxuUGF5ZWVGU1AtLT4-U3dpdGNoOioqSFRUUCAyMDIqKiAoQWNjZXB0ZWQpXG5QYXllZUZTUC0-UGF5ZWVGU1A6UGF5ZWUgRlNQIGRlY2lkZXMgdG8gZ2l2ZSAxIFVTRCBpbiBjb21taXNzaW9uXFxudG8gUGF5ZXIgKEFnZW50KSBzbyB0aGF0IENhc2gtSW4gb25seSBjb3N0cyAxIFVTRFxuUGF5ZWVGU1AtPj5QYXllZTpCeSBwYXlpbmcgMTAxIFVTRCBpbiBjYXNoIHRvIFBheWVyIChBZ2VudCksXFxueW91IHdpbGwgcmVjZWl2ZSAxMDAgVVNEIHRvIHlvdXIgYWNjb3VudFxuUGF5ZWUtPj5QYXllZUZTUDpPS1xuUGF5ZWVGU1AtPj5Td2l0Y2g6KipQVVQgL3F1b3RlcyoqXFxuKHRyYW5zZmVyQW1vdW50PTk5IFVTRCxcXG5wYXllZVJlY2VpdmVBbW91bnQ9MTAwXFxuVVNELCBwYXllZUZzcENvbW1pc3Npb249MSBVU0QpXG5Td2l0Y2gtLT4-UGF5ZWVGU1A6KipIVFRQIDIwMCoqIChPSylcbmRlYWN0aXZhdGUgUGF5ZWVGU1BcblN3aXRjaC0-PlBheWVyRlNQOioqUFVUIC9xdW90ZXMqKlxcbih0cmFuc2ZlckFtb3VudD05OSBVU0QsXFxucGF5ZWVSZWNlaXZlQW1vdW50PTEwMFxcblVTRCwgcGF5ZWVGc3BDb21taXNzaW9uPTEgVVNEKVxuUGF5ZXJGU1AtLT4-U3dpdGNoOioqSFRUUCAyMDAqKiAoT0spXG5kZWFjdGl2YXRlIFN3aXRjaFxuUGF5ZXJGU1AtPj5QYXllcjpQYXllZSB3aWxsIHJlY2VpdmUgMTAwIFVTRCBhbmQgZmVlIGlzIDEgVVNELFxcbnlvdSB3aWxsIHJlY2VpdmUgMSBVU0QgaW4gY29tbWlzc2lvblxuZGVhY3RpdmF0ZSBQYXllckZTUFxuUGF5ZXItPj5QYXllZU90YzpZb3Ugd2lsbCByZWNlaXZlIDEwMCBVU0Qgb24geW91ciBhY2NvdW50LFxcbnBsZWFzZSBnaXZlIG1lIDEwMSBVU0RcblBheWVlT3RjLT4-UGF5ZXI6T0ssIGhlcmUgaXMgMTAxIFVTRCBpbiBjYXNoXG5cblBheWVyLT4-UGF5ZXJGU1A6UGVyZm9ybSB0cmFuc2FjdGlvblxuYWN0aXZhdGUgUGF5ZXJGU1BcblBheWVyRlNQLT5QYXllckZTUDogUmVzZXJ2ZSAxIFVTRCBmcm9tIEFnZW50IGNvbW1pc3Npb24gdG8gUGF5ZXJcXG5hY2NvdW50LCAxMDAgVVNEIGZyb20gUGF5ZXIgYWNjb3VudCwgOTkgVVNEIHRvXFxuU3dpdGNoIGFjY291bnQgYW5kIDEgVVNEIHRvIGZlZSBhY2NvdW50LCAxIFVTRFxcbmZyb20gRlNQIGNvbW1pc3Npb24gYWNjb3VudCB0byBmZWUgYWNjb3VudFxuUGF5ZXJGU1AtPj5Td2l0Y2g6KipQT1NUIC90cmFuc2ZlcnMqKlxcbihhbW91bnQ9MTAwIFVTRClcbmFjdGl2YXRlIFN3aXRjaFxuU3dpdGNoLS0-PlBheWVyRlNQOioqSFRUUCAyMDIqKiAoQWNjZXB0ZWQpXG5Td2l0Y2gtPlN3aXRjaDpSZXNlcnZlIDk5IFVTRCBmcm9tIFBheWVyIEZTUFxcbmFjY291bnQgdG8gUGF5ZWUgRlNQIGFjY291bnRcblN3aXRjaC0-PlBheWVlRlNQOioqUE9TVCAvdHJhbnNmZXJzKipcXG4oYW1vdW50PTEwMCBVU0QpXG5hY3RpdmF0ZSBQYXllZUZTUFxuUGF5ZWVGU1AtLT4-U3dpdGNoOioqSFRUUCAyMDIqKiAoQWNjZXB0ZWQpXG5QYXllZUZTUC0-UGF5ZWVGU1A6VHJhbnNmZXIgOTkgVVNEIGZyb20gU3dpdGNoIGFjY291bnQgYW5kXFxuMSBVU0QgZnJvbSBpbnRlcm5hbCBjb21taXNzaW9uIGFjY291bnRcXG50byBQYXllZSBhY2NvdW50XG5QYXllZUZTUC0-PlBheWVlOllvdSBoYXZlIENhc2hlZC1pbiAxMDAgVVNEXG5QYXllZUZTUC0-PlN3aXRjaDoqKlBVVCAvdHJhbnNmZXJzKipcXG4oRnVsZmlsbWVudClcblN3aXRjaC0tPj5QYXllZUZTUDoqKkhUVFAgMjAwKiogKE9LKVxuZGVhY3RpdmF0ZSBQYXllZUZTUFxuU3dpdGNoLT5Td2l0Y2g6Q29tbWl0IHJlc2VydmVkIHRyYW5zZmVyXG5Td2l0Y2gtPj5QYXllckZTUDoqKlBVVCAvdHJhbnNmZXJzKipcXG4oRnVsZmlsbWVudClcblBheWVyRlNQLS0-PlN3aXRjaDoqKkhUVFAgMjAwKiogKE9LKVxuZGVhY3RpdmF0ZSBTd2l0Y2hcblBheWVyRlNQLT5QYXllckZTUDpDb21taXQgcmVzZXJ2ZWQgdHJhbnNmZXJcblBheWVyRlNQLT4-UGF5ZXI6VHJhbnNhY3Rpb24gc3VjY2Vzc2Z1bCwgeW91IGhhdmUgc2VudFxcbjEwMCBVU0QgYW5kIHJlY2VpdmVkIDEgVVNEIGluIGNvbW1pc3Npb25cbmRlYWN0aXZhdGUgUGF5ZXJGU1BcblBheWVyLT4-UGF5ZWVPdGM6VGhhbmsgeW91ISIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

I haven't played with theming to get the look to match above but the advantage of Mermaid is that it is Open Source and written in JS so would fit easily into our toolchain.

https://github.com/knsv/mermaid

**Comment by adrianhopebailie** [comment]
FYI: https://github.com/knsv/mermaid/issues/866

**Comment by ehenrka** [comment]
This is probably the closest I can get using PlantUML to the existing figures without spending too much time:

![Figure22](https://user-images.githubusercontent.com/30468528/64255187-2568b400-cf21-11e9-9c3a-499795b1d102.png)

[figure 22.txt](https://github.com/mojaloop/mojaloop-specification/files/3574499/figure.22.txt)

**Comment by elnyry** [comment]
@adrianhopebailie @ehenrka @MichaelJBRichards @MichaelJBRichards - any objections to closing this now? 

As discussed above, we're now using SVGs for hand drawn diagrams and plantuml (with enhancements for better rendering) for sequence diagrams, as can be seen in the API Definition markdown doc. Example of a sequence diagram is here: http://mojaloop.io/mojaloop-specification/documents/API%20Definition%20v1.0.html#figure-2 and you can review the rest of the document for other architecture (or other) and sequence diagrams.

**Comment by ehenrka** [comment]
Some immediate comments regarding just the linked figure:

- The height of the participant boxes should preferably be the same. Use for example `participant "\nFSP" as FSP` to get the same height as the `Optional Switch` which is in two rows.
- Related to above, compare `Peer FSP` in Figure 1 to Figure 2, in Figure 1 Peer FSP is in two rows while in Figure 2 it is in one row.
- Don't know if it is the font used, but it really looks like the word "service" is using capital I ("servIce"). At least this is an issue when using default zoom in Chrome (100%). Using for example 90% or 110% gives a correct lower case "i". Can we change the font?
- Again, don't know if it is a font issue but "HTTP 202 (Accepted)" looks like there is no whitespace between HTTP 202 and (Accepted).
- "Figure 2 -- HTTP GET call flow" Double "--" which seems unnecessary?
- Use `hide footbox` to remove participant boxes in the footer

**Comment by elnyry** [comment]
Thanks @ehenrka , will address these.

**Comment by ehenrka** [comment]
I also looked at an image that is not a sequence diagram, Figure 6, and there are a lot of misspellings of "commission", and the shape depicting the Switch is very strange. The original image should be convertable to PNG in a good enough quality. I do not really see the reason for using SVG for that kind of figure.

**Comment by ehenrka** [comment]
Some additional comments after looking at some random sections:

- 5.1.6.9 ATM-Initiated Cash-Out** <-- two stars (*) after section name
- There seems to be two delays added in Figure 34, between "Payer fee is 1 USD in Payer FSP
for ATM Cash-Out, total fee 2 USD" and "OTP is pre-generated", and similarly between "Validate OTP sent by Payee FSP, OTP OK" and "Reserve 102 USD from Payer account, 101 USD to Switch account, 1 USD to fee account". There should not be any delays. This seeems to be present in other figures as well  (for example Figure 36, 46, 51, 52, 66). Please see the answer in https://forum.plantuml.net/4595/deactivating-immediately-activating-lifeline-sequence-diagrams how you can deactivate and then activate a lifeline (I can verify that it works).
- There seems to be some extra whitespace in at least Figure 34 and 36 in "PUT /transfers/<ID>" between the "PUT /transfers/" and "<ID>".
- Misspelling in Figure 36, "Generated OTP, "12345"" should be "Generate OTP, "12345""
- Listing 12 is strange with double * instead of bold.
- 6.3.4.1, "Alternative URI: PUT /parties/{Type}/{ID}/{SubId}/error**" <-- double *
- 7.2.3.1 Regular Expression** <-- double **
- 7.2.4.1 Regular Expression** <-- double **
- 7.2.5.1 Regular Expression** <-- double **

**Comment by elnyry** [comment]
Thanks @ehenrka , these issues are being addressed via PR: https://github.com/mojaloop/mojaloop-specification/pull/45 (Henk a colleague is on it)

**Comment by elnyry-sam-k** [comment]
As discussed above, settled on `SVG` format (using tools such as draw.io, etc) for hand-drawn diagrams and `plantuml` for traditional sequence diagrams with some formatting (as discussed above)
