### ISSUE TITLE
Solution Proposal: Notify Payee FSP in case of failure to commit on a Switch

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/mojaloop-specification#106]
## **\[103\] -- \[Notify Payee FSP in case of failure to commit on a Switch\]**
___

### **Table of Contents**

- [1. Preface](#1.-preface)
  - [1.1 Solution Proposal Information](#1.1-solution-proposal-information)
  * [1.2 Document Version Information](#1.2-document-version-information)
* [2. Change Request](#2.-change-request)
  * [2.1 Background](#2.1-background)
* [3. Proposed Solution](#3.-proposed-solution)
  * [3.1 Specify how IDs can be generated](#3.1-specify-how-ids-can-be-generated)
  * [3.2 Add quote ID to POST /transfers data model](#3.2-add-quote-id-to-post-transfers-data-model)
* [4. Other Considered Solutions](#4.-other-considered-solutions)
  * [4.1 Add transaction ID to the POST /transfers data model](#4.1-add-transaction-id-to-the-post-transfers-data-model)
  * [4.2 Force the Payer FSP to use the transaction ID as transfer ID](#4.2-force-the-payer-fsp-to-use-the-transaction-id-as-transfer-id)

<h2 id="1.-preface">1. Preface</h2>
___

This section contains basic information regarding the solution proposal.

<h4 id="1.1-solution-proposal-information">1.1 Solution Proposal Information</h4>

| | |
|---|---|
| Change Request ID | 103 |
| Change Request Name | Notify Payee FSP in case of failure to commit on a Switch |
| Prepared By | Sam Kummary, ModusBox |
| Solution Proposal Status | In review [x] / Approved [ ] / Rejected [ ] |
| Approved/Rejected Date |

<h4 id="1.2-document-version-information">1.2 Document Version Information</h4>

| Version | Date | Author | Change Description |
|---|---|---|---|
| 1.0 | 2021-12-14 | Sam Kummary| Initial version of the solution proposal. Sent out for review. |

<h2 id="2.-change-request">2. Change Request</h2>
___

<h4 id="2.1-background">2.1 Background</h4>

This issue is about handling error cases that happen during processing of PUT /transfers/{ID} calls. Specifically, about how a Switch should deal with a scenario when a validation error occurs during processing of a PUT /transfers/{ID} call. 

Here's the change request: https://github.com/mojaloop/mojaloop-specification/issues/103 for further details of the requirement / problem statement.

It was agreed by the CCB to adopt the approach below (as can be seen in the comments of the above change request)

A new method of notification with HTTP PATCH on `/transfers/{ID}/error` will be introduced, when there is an internal validation error (not schema validation) in the PUT `/transfers/{ID}` sent from the Payee FSP, both when RESERVED and COMMITTED is used as transferState.

To avoid major changes with minor versions, here's the adopted approach:
- Version 1.2 of the API supports sending PATCH /transfers/{ID}/error from the Switch in case the Payee FSP is using PUT /transfers/{ID} with COMMITTED and the commit failed in the Switch.
- No change for PUT /transfers/{ID} with RESERVED as the Payee FSP is expecting a PATCH /transfers/{ID} with either COMMITTED or ABORTED in version 1.1.
- Version 2.0 of the API adds same possibility of sending PATCH /transfers/{ID}/error from the Switch in case the Payee FSP is using PUT /transfers/{ID} with RESERVED and there is an error.

<h2 id="3.-proposed-solution">3. Proposed Solution</h2>
___

Pull request: https://github.com/mojaloop/mojaloop-specification/pull/109 shows the changes proposed

<h2 id="4.-other-considered-solutions">4. Other Considered Solutions</h2>
___

One of the alternatives considered was proposed for 2.0 as a breaking change. 

Version 2.0 of the API adds the same possibility of sending `PATCH /transfers/{ID}/error` from the Switch in case the Payee FSP is using `PUT /transfers/{ID}` with RESERVED and there is an error.

**Comment by henrka** [comment]
@elnyry-sam-k, I think this one can be closed?

**Comment by elnyry-sam-k** [comment]
Yes @henrka , thanks!

**Comment by henrka** [comment]
Closed as discussed above.
