### ISSUE TITLE
Change Request: Uniquely identifying requests in the /participants endpoint

### ISSUE THREAD

**Issue by MichaelJBRichards** [mojaloop/mojaloop-specification#115]
### **Table of Contents**

* [1. Preface](#1.-preface)
  * [1.1 Change Request Information](#1.1-change-request-information)
  * [1.2 Document Version Information](#1.2-document-version-information)
* [2. Problem Description](#2.-problem-description)
  * [2.1 Background](#2.1-background)
  * [2.2 Current Behaviour](#2.2-current-behaviour)
  * [2.3 Requested Behaviour](#2.3-requested-behaviour)
* [3 Proposed Solution Options](#3.-proposed-solution-options)

<h2 id="1.-preface">1. Preface</h2>
___

This section contains basic information regarding the change request.

<h4 id="1.1-change-request-information">1.1 Change Request Information</h4>

| Requested By | Michael Richards, ModusBox |
| Change Request Status | In review ☒  / Approved ☐ / Rejected ☐ |
| Approved/Rejected Date |   |

<h4 id="1.2-document-version-information">1.2 Document Version Information</h4>

| Version | Date | Author | Change Description |
| --- | --- | --- | --- |
| 1.0 | 2022-09-13 | Michael Richards | Initial version of template. Sent out for review. |

<h2 id="2.-problem-description">2. Problem Description</h2>
___

<h4 id="2.1-background">2.1 Background</h4>

There is a problem with duplicate identifiers in Mojaloop. There are good reasons why more than one participant in a Mojaloop scheme might claim the same identifier - for instance, when Mobile Money schemes are operated by entities who are not Mobile Network Operators. As part of Mojaloop's efforts to address this issue, we intend to implement a use case which will allow customers themselves to use their DFSP request that their account at a particular DFSP be made the default for transfers to them, and to allow the Mojaloop switch to obtain direct confirmation from the customer that they have assented to the DFSP's request in the form of an OTP.

Use of an OTP requires confirmation via the existing **/authorizations** endpoint in the FSPIOP API, but this endpoint requires identification of the request (normally a **/transactionRequests** request) for which authorisation is required. However, the **/participants** endpoint, which is the FSPIOP API endpoint which is used to request assignment of an identifier to a DFSP, does not currently include a way of identifying a particular request, such as is provided, for instance, by the _quoteId_ field in the **/quotes** endpoint. We therefore need a way of assigning a unique ID to a request to register an identifier with a DFSP. 

<h4 id="2.2-current-behaviour">2.2 Current Behaviour</h4>

At present, there are two ways of requesting assignment of an identifier to a DFSP. The long form, described in Section 6.2.3.3 of the FSPIOP specification, makes the entire request in the command: for instance, **POST /participants/MSISDN/123456**. The second form, described in Section 6.2.3.2 of the FSPIOP specification, contains one or more identifiers in the body of the request, and uses the simple command form **POST /participants**. The second form does contain an identifier in the form of the _requestId_ field, but this identifier relates to the batch of requests, and not to the individual request.

<h4 id="2.3-requested-behaviour">2.3 Requested Behaviour</h4>

There are a number of ways in which this problem could be solved. One would be to add a unique identifier to the existing endpoints. The long form of assignment might take the form **POST /f9357e7f-4552-4b89-966e-b7764419fde8/participants/MSISDN/123456**, where _f9357e7f-4552-4b89-966e-b7764419fde8_ is the unique identifier assigned by the requesting DFSP. The short form of the request might add a unique identifier to each assignment request in the _partyList_, either by adding a unique identifier to the _partyIdInfo_ object or, probably more securely, by creating a new composite object which contained a correlation ID for the request and a _partyIdInfo_ object. Doubtless other solutions might also work; I leave these for discussion.

**Comment by ehenrka** [comment]
With "long form", I assume you mean **POST /participants/**_type_**/**_identifier_?

In my view, **POST /participants/**_type_**/**_identifier_ would be what is used the most as you most often just update a single account holder's default identifier. The **POST /participants** would mostly be used just for the first time when the FSP connects to the scheme, to create identifiers for each account holder in the system.

If we should remove one of these, it would make more sense for me to remove the **POST /participants**.  Account holders should then preferably register themselves in the scheme using **POST /participants/**_type_**/**_identifier_, either directly from their FSP or in some common account lookup service (with or without OTP confirmation based on scheme preferences). I don't have any issue with keeping both **POST /participants/**_type_**/**_identifier_ and **POST /participants** though.

**Comment by henrka** [comment]
@MichaelJBRichards, gentle reminder to respond to this CR if it's still valid and something that you would like to change.

**Comment by henrka** [comment]
Closing as discussed on today's FSPIOP SIG meeting.
