### ISSUE TITLE
Change Request: Should the response to a GET /parties contain a correlation ID?

### ISSUE THREAD

**Issue by MichaelJBRichards** [mojaloop/mojaloop-specification#121]
### **Table of Contents**

* [1. Preface](#1.-preface)
  * [1.1 Change Request Information](#1.1-change-request-information)
  * [1.2 Document Version Information](#1.2-document-version-information)
* [2. Problem Description](#2.-problem-description)
  * [2.1 Background](#2.1-background)
  * [2.2 Current Behaviour](#2.2-current-behaviour)
  * [2.3 Requested Behaviour](#2.3-requested-behaviour)
* [3 Proposed Solution Options](#3.-proposed-solution-options)

<h2 id="1.-preface">1. Preface</h2>
___

This section contains basic information regarding the change request.

<h4 id="1.1-change-request-information">1.1 Change Request Information</h4>

| Requested By | Michael Richards, Infitx |
| Change Request Status | In review ☒  / Approved ☐ / Rejected ☐ |
| Approved/Rejected Date |   |

<h4 id="1.2-document-version-information">1.2 Document Version Information</h4>

| Version | Date | Author | Change Description |
| --- | --- | --- | --- |
| 1.0 | 2023-05-18| Michael Richards | Initial version. Sent out for review. |

<h2 id="2.-problem-description">2. Problem Description</h2>
___

<h4 id="2.1-background">2.1 Background</h4>

At present, the response to a **GET /parties**  or a **GET /participants** request does not contain a correlation ID. Although the recipient can ascertain from the non-repudiation signature that the sender was the institution they purported to be, and that the message had not been modified in transit, there is no ready way to distinguish different responses from each other. This may become a question of importance if disputes arise, for instance, about how participant DFSPs respond to requests to transfer funds to a customer whose account is in  the process of suspension or reinstatement. 

<h4 id="2.2-current-behaviour">2.2 Current Behaviour</h4>

At present, neither the **PUT /parties** response nor the **PUT /participants** response contains an identifier. It is not possible, therefore, to distinguish responses from each other.

<h4 id="2.3-requested-behaviour">2.3 Requested Behaviour</h4>

Explain how you would like the API to behave.

The response to a request for information about a customer should be accompanied by a correlation ID which will allow both parties to identify the response which was used as the basis for an action.

<h2 id="3.-proposed-solution-options">3. Proposed Solution Options</h2>
___

Include an optional _identificationId_ (of type _CorrelationId_) in the **PUT /parties**  and **PUT /participants** API definitions.

**Comment by henrka** [comment]
Thanks @MichaelJBRichards, I'm not exactly following why this is necessary though from the sentence below:

> This may become a question of importance if disputes arise, for instance, about how participant DFSPs respond to requests to transfer funds to a customer whose account is in the process of suspension or reinstatement.

The **/parties** and **/participants** resources are not meant for transferring. If the Payee's account is for example suspended or blocked, then the the Payee FSP should just reject the quote. Can you please explain the use case for a correlation ID in these resources in more detail?

**Comment by elnyry-sam-k** [comment]
There's also an issue (when we were using word documents at CCB) when this (or similar) issue raised. I lost access to some earlier docs but may be @henrka or @MichaelJBRichards you still have that Change request in word document form.

**Comment by henrka** [comment]
As discussed in the FSPIOP API SIG meeting today, the proposal is to close this one as you could use #71 to trace the messages if required.

**Comment by henrka** [comment]
Closing as discussed on today's call
