### ISSUE TITLE
Change Request: Co-ordinating Transfer Time-outs

### ISSUE THREAD

**Issue by MichaelJBRichards** [mojaloop/mojaloop-specification#122]
### **Table of Contents**

* [1. Preface](#1.-preface)
  * [1.1 Change Request Information](#1.1-change-request-information)
  * [1.2 Document Version Information](#1.2-document-version-information)
* [2. Problem Description](#2.-problem-description)
  * [2.1 Background](#2.1-background)
  * [2.2 Current Behaviour](#2.2-current-behaviour)
  * [2.3 Requested Behaviour](#2.3-requested-behaviour)
* [3 Proposed Solution Options](#3.-proposed-solution-options)

<h2 id="1.-preface">1. Preface</h2>
___

This section contains basic information regarding the change request.

<h4 id="1.1-change-request-information">1.1 Change Request Information</h4>

| Requested By | Michael Richards, INFITX |
| Change Request Status | In review ☒  / Approved ☐ / Rejected ☐ |
| Approved/Rejected Date |   |

<h4 id="1.2-document-version-information">1.2 Document Version Information</h4>

| Version | Date | Author | Change Description |
| --- | --- | --- | --- |
| 1.0 | 2023-05-31 | Michael Richards | Initial version. Sent out for review. |

<h2 id="2.-problem-description">2. Problem Description</h2>
___

<h4 id="2.1-background">2.1 Background</h4>

This change request transfers an issue originally raised with the DA (DA issue 61). The DA's view is that it should properly be considered by the FSPIOP SIG.

At present, the switch is responsible for timing a transfer out. We therefore ask the payer DFSP to issue a GET /transfers before timing out at their end, to ensure that they only time transfers out if the switch has timed them out first. However, it is still possible for the switch to time a transfer out while the payee DFSP is still responding to it; and, given that the payee DFSP may clear funds to the payee account immediately and without waiting for confirmation from the switch, it is possible that funds may be disbursed to the customer by the payee DFSP without those funds being guaranteed by the switch's settlement records.

We should, perhaps, ask the switch to issue a GET /transfers to the payee DFSP before timing out. If a timely response is not received, or if the payee wants to abort the transfer, then the switch can go ahead and time it out. This articulates a general principle: an upstream participant should not time a transfer out without first seeking approval from the next downstream party.

This idea is also based around the proposal that the function of timing out is to ensure that transfers aren't left in limbo if one of the parties goes offline. Timing out is not, according to this idea, a way of ensuring that parties adhere to their response SLAs

Further discussion from the DA:

The group agreed that there needs to be a balance between the need to eliminate reconciliation and liquidity management of (Payer) FSPs by not holding/reserving funds for longer than necessary. In addition, It was proposed to use 'grace time period' before timing out transfers to compensate for differences in clocks. It was also suggested that for risky transactions, the final notification in the form of a PATCH call that was introduced with FSPIOP API v1.1 can be used to mitigate risk to the Payee FSPs.

One point made was that after the timeout period (plus the grace period to account for clock difference), a transfer status cannot be changed - it is either finalized or it isn't, but it cannot be changed. For example, if a timeout period (expressed as a time in future and not duration) is 10 seconds, then a Payer FSP (or Switch), may add a grace period of 1second and after waiting for 11seconds can query the downstream entity to find the transfer's status; At this point, if a transfer is finalized (Committed or Aborted), then the Payer FSP can take action accordingly; however if it is in an intermediate state, then the transfer has to be timed-out since the time-out period is done.

The group agreed on the need to revisit the topic of implementing 'telescopic timeouts', which is not currently supported in favor of end-to-end encryption of (most) messages.

<h4 id="2.2-current-behaviour">2.2 Current Behaviour</h4>

Explain how the API currently behaves.

See above

Explain how you would like the API to behave.

This is for discussion

<h2 id="3.-proposed-solution-options">3. Proposed Solution Options</h2>
___

**Comment by henrka** [comment]
Please find some comments/questions below. Generally I don't really see this as an issue in FSPIOP API, more in the Mojaloop Switch implementation, except for the current signature functionality that prevents telescoping timeouts.

> At present, the switch is responsible for timing a transfer out.

This is not mandated by the FSPIOP API as far as I know. There shouldn't be anything in the specification saying that it is the Switch that is responsible for timing a transfer out, that sounds like a decision by the Mojaloop Switch implementation. It could as well be the Payer FSP that times out the transfer if you follow the API. Can you please point to where it is described in the FSPIOP API that the Switch is responsible for timing a transfer out?

> We should, perhaps, ask the switch to issue a GET /transfers to the payee DFSP before timing out.

It is already mentioned as a generic good practice in the API in https://docs.mojaloop.io/api/fspiop/v1.1/api-definition.html#server-missing-response-from-client if you don't get a callback within a reasonable time.

> For example, if a timeout period (expressed as a time in future and not duration) is 10 seconds, then a Payer FSP (or Switch), may add a grace period of 1second and after waiting for 11seconds can query the downstream entity to find the transfer's status

See for example note in https://docs.mojaloop.io/api/fspiop/v1.1/api-definition.html#timeout-and-expiry.

> The group agreed on the need to revisit the topic of implementing 'telescopic timeouts', which is not currently supported in favor of end-to-end encryption of (most) messages.

Encryption is done on parameter level, I guess you mean end-to-end integrity and non-repudiation through the current signature functionality?

**Comment by henrka** [comment]
@MichaelJBRichards, suggesting to close this one and start a specific change request on an improved signing feature, as also discussed in #118. Or do you think that there are still other open points that have not been addressed in my comment above (https://github.com/mojaloop/mojaloop-specification/issues/122#issuecomment-1573190810)?

**Comment by henrka** [comment]
Closing as discussed on today's FSPIOP SIG meeting. Separate change request on improved signing feature can be created when needed.
