### ISSUE TITLE
Change Request: Possibility to notify Payee FSP on successful commit in Switch 

### ISSUE THREAD

**Issue by ehenrka** [mojaloop/mojaloop-specification#29]
# _29 – Possibility to notify Payee FSP on successful commit in Switch_

### **Table of Contents**

* [Preface](#preface)
  * [Change Request Information](#change-request-information)
  * [Document Version Information](#document-version-information)
* [Problem Description](#problem-description)
  * [Background](#background)
  * [Current Behaviour](#current-behaviour)
  * [Requested Behaviour](#requested-behaviour)
* [Proposed Solution Options](#proposed-solution-options)

## **Preface**
___

This section contains basic information regarding the change request.

### Change Request Information

| Change Request ID | 29|
| --- | --- |
| Change Request Name | Possibility to notify Payee FSP on successful commit in Switch|
| Requested By | Henrik Karlsson, Ericsson |
| Change Request Status | In review ☒  / Approved ☐ / Rejected ☐ |
| Approved/Rejected Date |   |

### Document Version Information

| Version | Date | Author | Change Description |
| --- | --- | --- | --- |
| 1.0 | 2019-11-04 | Henrik Karlsson | Initial version. Sent out for review. |

## **Problem Description**
___

### Background

In order for a Payee FSP to ascertain that a transfer has been committed successfully in the Switch, the Payee FSP today needs to send a **GET /transfers/**<_ID_> to the Switch as detailed in Section 6.7.1.6 in the _API Definition_. The functionality to check the status is important for some use cases where it is complicated to perform a refund in case of problems, for example in cash-out or merchant payment use cases where the funds are paid out in cash or the funds are used to purchase goods or services. To avoid having to send the **GET /transfers/**<_ID_>, the change request is to allow the Payee FSP to tell the Switch that the funds have been reserved, and the Switch will then send a notification to the Payee FSP when the transfer is committed in the Switch.

### Current Behaviour

The Payee FSP today needs to send a **GET /transfers/**<_ID_> to the Switch to know the status in the Switch. 

### Requested Behaviour

The Payee FSP can send the **PUT /transfers/**<_ID_> to the Switch saying that the funds are reserved and that it would like a notification when the transfer is committed in the Switch.

## **Proposed Solution Options**

To indicate that the Payee FSP would like to have a notification regarding the status in the Switch before it will commit the transfer (the transfer must be reserved in the Payee FSP), the Payee FSP should send a **PUT /transfers/**<_ID_> with the transferState set to `RESERVED` instead, and no `completedTimestamp `as the transfer is not yet completed:

```
PUT /transfers/85feac2f-39b2-491b-817e-4a03203d4f14 HTTP/1.1
Content-Type: application/vnd.interoperability.transfers+json;version=1.0
Content-Length: 166
Date: Tue, 15 Oct 2019 08:14:02 GMT
FSPIOP-Source: DFSP2
FSPIOP-Destination: DFSP1
FSPIOP-Signature: {"signature": "YXBwbGlj...JzK2pzb2"}
{
"fulfilment": "mhPUT9ZAwd-BXLfeSd7-YPh46rBWRNBiTCSWjpku90s",
"transferState": "RESERVED",
}
```

Switch receives the **PUT /transfers/**<_ID_>, responds with `HTTP 200` as normal. Switch then looks at the `transferState `element:
•	If transfer state is `COMMITTED`, then there is no need to send out a notification as the Payee FSP has already accepted the risk that the transfer in some rare cases might fail. This is how it works in the API today.
•	If transfer state is `RESERVED`, then the Switch needs to send out a notification when the transfer is committed in the Switch.

If the Switch should send out a notification (transfer state is `RESERVED`), the “JSON Merge Patch” standard as defined in https://tools.ietf.org/html/rfc7386 is used (except that we should continue to use the `Content-Type` header from the API). This is the simplistic version for patching existing JSON instead of the more complex “JSON Patch” standard (https://tools.ietf.org/html/rfc6902). JSON Merge Patch allows the Switch in a standardized way to just send out the elements that should be changed, i.e. the `completedTimestamp `and the `transferState`. Example:

```
PATCH /transfers/85feac2f-39b2-491b-817e-4a03203d4f14 HTTP/1.1
Content-Type: application/vnd.interoperability.transfers+json;version=1.0
Content-Length: 166
Date: Tue, 15 Oct 2019 08:14:03 GMT
FSPIOP-Source: Switch
FSPIOP-Destination: DFSP2
FSPIOP-Signature: {"signature": "YXBwbGlj...JzK2pzb2"}
{
"completedTimestamp": "2019-10-15T08:14:03.113+01:00",
"transferState": "COMMITTED",
}
```

When the Payee FSP receives the **PATCH /transfers/**<_ID_> notification, it responds with `HTTP 200`, and then either:
•	If the `transferState `is set to `COMMITTED`, the Payee FSP commits the transfer
•	If the `transferState `is set to `ABORTED`, the Payee FSP cancels the reserved transfers and aborts the transaction

If the Payee FSP does not get the notification from the Switch within a reasonable time, it can resend the **PUT /transfers/**<_ID_> to the Switch as the request should be idempotent. The Switch should then send (or resend) the **PATCH /transfers/**<_ID_>  to the Payee regarding the status in the Switch. This is to align the flow with all other requests that can be resent to request a new callback (see for example Section 9.4 in API Definition).

The Payee FSP will need to receive the status from the Switch before committing, or accept the risk that the transfer in the Switch might have failed. The Payee FSP should not be allowed to abort the transaction without receiving an `ABORTED `state from the Switch, as the Payee FSP has sent the fulfilment (which is the commit trigger) to the Switch.

The suggested sequence flow for the communication between the Switch and the Payee FSP:
![InteroperabilityFXTransferPayeeFspReserve](https://user-images.githubusercontent.com/30468528/68112664-1b980880-fef2-11e9-9a14-0291070b02ae.png)
___

**Comment by jmssebunnya** [comment]
Aligned and Support to have this implementation with PATCH /transfers/<ID> notification

**Comment by ehenrka** [comment]
A gentle reminder to all assignees regarding review of this change request..

**Comment by millerabel** [comment]
Thanks for the nudge, I’ll have a look tomorrow. 

— Miller

On Nov 26, 2019, at 1:52 AM, Henrik Karlsson <notifications@github.com> wrote:

A gentle reminder to all assignees regarding review of this change request..

**Comment by millerabel** [comment]
**I support this change.** This is an elegant way to conduct and track the progressive state change for selected use cases.

I would suggest, however, looking at the state labels that are used in the normal case: 

In the bilateral arrangement, PUT COMMITTED (as written in the spec) makes sense since the payee commits the transfer in its own books.

However, when the optional switch is present, it would be more accurate to have payee PUT “FULFILLED” since only the switch can COMMIT the transfer for settlement. This indicates the unstable state of the transfer— payee has already paid out (I.e. fulfilled) when requesting clearing of the transfer. Next state entered by the switch is either COMMITTED or ABORTED.

**Comment by ehenrka** [comment]
Thanks Miller,

I fully understand your view on fulfilled vs committed, but in the FSP's view the transfer is committed in their system so I don't see it as incorrect as it is now. The description of the possible transfer states in Figure 55 is also saying "Next ledger successfully performed the transfer", as such the state only represents the local ledger's state, not the switch ledger's state of the transfer.  Using state **FULFILLED** would require a new major version of the API, as that state does not exist in the current version major version (1).

**Comment by millerabel** [comment]
Hi Henrik, I’m sensitive to the fact this would be a major change, but it appears also as a disconnect with how a switch-based scheme will view the state of a transfer.

In switch-based schemes, a transfer is not actually “committed” in the DFSP. Transaction requirements may be fulfilled, pending commitment by the switch. But if the switch can’t commit, it will abort the transfer. Once committed, a transfer can not be aborted. “Committed” is a terminal state.

In the bilateral case, your description is correct. The DFSP commits the funds in its own books and the transfer can no longer be aborted. The bilateral notification to the payer that a transfer is committed is a terminal state within the bilateral scheme.

The issue becomes clear when the payee DFSP asks the switch what the state of a transfer is. If the switch says it is committed, that means it is scheduled for settlement and the transfer is final. But if the transfer has not yet been committed within the switch, what state will the switch report to the payee DFSP?

So I think this is a material difference between how bilateral and switched schemes progress transfers that requires clarification within the system. We can take this up separately as it does not have any impact to the CR on this thread. Perhaps we should separate this to a separate issue?

— Miller


> On Feb 24, 2020, at 10:34 AM, Henrik Karlsson <notifications@github.com> wrote:
> 

﻿
Thanks Miller,

I fully understand your view on fulfilled vs committed, but in the FSP's view the transfer is committed in their system so I don't see it as incorrect as it is now. The description of the possible transfer states in Figure 55 is also saying "Next ledger successfully performed the transfer", as such the state only represents the local ledger's state, not the switch ledger's state of the transfer. Using state FULFILLED would require a new major version of the API, as that state does not exist in the current version major version (1).

**Comment by ehenrka** [comment]
Thanks for the additional information. 

The transfer is committed in at least our system, we don't discern based on if it's a bilateral or switch-based scheme. If there would be a problem later with a transfer, it can be manually handled (e.g. refunded or reversed) by customer care, similar to other internal transactions. There is no difference in this between a bilateral or switch-based transfer in our system, both of them can be manually handled if there is a need for it.

> The issue becomes clear when the payee DFSP asks the switch what the state of a transfer is. If the switch says it is committed, that means it is scheduled for settlement and the transfer is final. But if the transfer has not yet been committed within the switch, what state will the switch report to the payee DFSP?

What is said in the specification is that the switch should only return the finalized (terminal) state. It should wait with sending the callback to the FSP until it knows the finalized state. Excerpt from Section 6.7.1.6:
"If the **GET /transfers/**<_ID_> is received by the Switch after **PUT /transfers/**<_ID_> from the Payee FSP, but before clearing has completed, the Switch should wait with sending the callback until clearing has completed with either a successful or unsuccessful result. If clearing has already occurred (as shown in Figure 53), the **PUT /transfers/**<_ID_> callback can be sent immediately."

> We can take this up separately as it does not have any impact to the CR on this thread. Perhaps we should separate this to a separate issue?

Sounds great, let's discuss further in a separate issue.

**Comment by bushjames** [comment]
A note to not forget about backward compatibility when this change comes ready for implementation.

Assuming this change becomes part of an API spec version iteration, there is a need to allow DFSPs on the existing v1.0 version of the spec to co-exist with switch and other DFSPs who support the new model. This comes back to the points raised during the Jan 2020 Johannesburg convening about API versioning, upgrade path and backward compatibility.

**Comment by elnyry** [comment]
@bushjames thanks. This (compatibility) has been (and will be) one of the primary considerations regarding this.

**Comment by elnyry-sam-k** [comment]
This is now included in the Mojaloop FSP Interoperability API v1.1. 

Before closing I had a question - can this be applied to bulk transfers as well? If so, at bulk level or individual transfer level, will raise it in the next CCB meeting.

**Comment by ehenrka** [comment]
@elnyry-sam-k:
> Before closing I had a question - can this be applied to bulk transfers as well? If so, at bulk level or individual transfer level, will raise it in the next CCB meeting.

No, not without major changes to the API. The **BulkTransferState** does not have a similar RESERVED state, and the **IndividualTransferResult** does not contain a state (they are either fulfilled or rejected).

**Comment by elnyry-sam-k** [comment]
Ok, thanks @ehenrka
