### ISSUE TITLE
Incorrect use of Unicode encoded equals sign ('\u003d' instead of '=') in the end-to-end example

### ISSUE THREAD

**Issue by ehenrka** [mojaloop/mojaloop-specification#31]
**Describe the bug**
Section 10 (End-to-End Example) incorrectly uses unicode encoded equals sign. The `IlpPacket` in Listings 45, 47, and 49 should end with `...==` instead of `...\u003d\u003d`. `\u003d` is `=` in unicode.

**Expected behavior**
`\u003d` should be `=` in Listing 45, 47, and 49.

**Comment by elnyry** [comment]
Included in v1.1 draft #52
