### ISSUE TITLE
Describe quote rejection for Payer initiated transaction in API Definition document

### ISSUE THREAD

**Issue by ehenrka** [mojaloop/mojaloop-specification#43]
**Describe the bug**
The _API Definition_ document does not clearly state what should happen if a Payer or Payer FSP rejects a quote. The process is described in the _Generic Transaction Patterns_ document, Section 4.1.4 step 15:

`The Payer is assumed to approve the transaction in this sequence. If the Payer would reject the transaction at this stage, no response regarding the rejection is sent to the Payee FSP. The created quote at the Payee FSP should have an expiry time, at which time it is automatically deleted.`

The same as above should be described in the _API Definition_ document.

**Comment by ehenrka** [comment]
Suggesting to add a new section under 6.5 (API Resource /quotes) between existing Section 6.5.2.1 and 6.5.1.1 (Quote Expiry Details) and 6.5.1.2 (Interledger Payment Request, this section then becomes 6.5.1.3 instead):

> 6.5.1.2	Rejection of Quote
The Payee FSP can reject a quote request from the Payer FSP by sending the error callback **PUT /quotes/**<_ID_>**/error** instead of the callback **PUT /quotes/**<_ID_>.<br>
Depending on which generic transaction pattern (see Section 8 for more information) that is used, the Payer FSP can reject a quote using one of the following processes:
•	If the transaction is initiated by the Payer (see Section 8.1), the Payer FSP should not inform the Payee FSP regarding the rejection. The quote that was created at the Payee FSP should have an expiry time, at which time it is automatically deleted.
•	If the transaction is initiated by the Payee (see Section 8.2 and 8.3), the Payer FSP should inform the Payee FSP regarding the rejection using the callback **PUT /transactionRequests/**<_ID_> with a rejected state. The process is described in more detail in Section 6.4.1.1.

**Comment by elnyry** [comment]
Added (by Henrik) to the draft of v1.1 that will be reviewed soon

**Comment by elnyry-sam-k** [comment]
Fixed with v1.1
