### ISSUE TITLE
Clarification needed: Interpretation of the Data Model for the ExtensionList element

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/mojaloop-specification#51]
### **Table of Contents**

* [1. Preface](#1.-preface)
  * [1.1 Change Request Information](#1.1-change-request-information)
  * [1.2 Document Version Information](#1.2-document-version-information)
* [2. Problem Description](#2.-problem-description)
  * [2.1 Background](#2.1-background)
  * [2.2 Current Behaviour](#2.2-current-behaviour)
  * [2.3 Requested Behaviour](#2.3-requested-behaviour)
* [3 Proposed Solution Options](#3.-proposed-solution-options)

<h2 id="1.-preface">1. Preface</h2>
___

This section contains basic information regarding the change request.

<h4 id="1.1-change-request-information">1.1 Change Request Information</h4>

| Requested By | Change Request Status |  Approved/Rejected Date |   
| --- | --- | --- |
| Sam Kummary, ModusBox | In review ☒  / Approved ☐ / Rejected ☐ | |

<h4 id="1.2-document-version-information">1.2 Document Version Information</h4>

| Version | Date | Author | Change Description |
| --- | --- | --- | --- |
| 1.0 | 2020-02-20 | Sam Kummary | Initial version. Discussed with CCB on 11Feb2020 |

<h2 id="2.-problem-description">2. Problem Description</h2>
___

<h4 id="2.1-background">2.1 Background</h4>

This is regarding the interpretation of the **extensionList** element's Data Model, from sections [7.4.4](https://github.com/mojaloop/mojaloop-specification/blob/master/documents/API%20Definition%20v1.0.md#744-extensionlist) of the [API Definition v1.0](https://github.com/mojaloop/mojaloop-specification/blob/master/documents/API%20Definition%20v1.0.md). This element is present in several complex data structures used for quotes, transfers, error information and such others.

<h4 id="2.2-current-behaviour">2.2 Current Behaviour</h4>

For ease of reference, here's the data model for `extensionList` (Section 7.4.4), taken from the API Definition v1.0 document.

#### _ExtensionList_

_[Table 72](#table-72) contains the data model for the complex type **ExtensionList**._

###### _Table 72_

_| **Name** | **Cardinality** | **Format** | **Description** |
| --- | --- | --- | --- |
| **extension** | 1..16 | Extension | Number of Extension elements. |_

A representation of this in a Open API / Swagger looks like below:
```
extensionList:
{
  extension:
  [ 
    { 
      “key”: “item1”, 
      “value”: “Description for item1” 
    }, 
    { 
      “key”: “item2”, 
      “value”: “Description for item2” 
    }
  ]
}
```

This is how the current v1.0 Swagger (a supporting file of the Specification document set) represents the **_extensionList_** element, as can be seen [here](https://github.com/mojaloop/mojaloop-specification/blob/89f9a4799984680daf15d8b3cb69a969709bb9be/Supporting%20Files/fspiop-rest-v1.0-OpenAPI-implementation.yaml#L1058).

However, some of the examples given in the Specification document set indicate either a different interpretation of the data model definition or an error, which is making this ambiguous.

1. Here's an example from the **_API Definition_**: 
https://github.com/mojaloop/mojaloop-specification/blob/master/documents/API%20Definition%20v1.0.md#listing-5
```
{
    "errorInformation": {
        "errorCode": "3001",
        "errorDescription": "The Client requested an unsupported version, see exten-
sion list for supported version(s).",
        "extensionList": [
            { "key": "1", "value": "0"},
            { "key": "2", "value": "1"},
            { "key": "4", "value": "2"},
        ]
    }
}
```

2. Here's another example from the **_Encryption_** document:
https://github.com/mojaloop/mojaloop-specification/blob/master/documents/Encryption.md#41-encryption-example
```
"extensionList": [
        { "value": "value1", "key": "key1"},
        { "value": "value2", "key": "key2"},
        { "value": "value3", "key": "key3" }
    ]
```

<h4 id="2.3-requested-behaviour">2.3 Requested Behaviour</h4>

There seems to be a need to clarify the data model so that it eliminates ambiguity. This may be done by providing examples of each type, one each for Simple, Complex types and some others so that they can be representative of how the data model definitions are to be interpreted.

It may also be moved to the **_proposed_** "Implementation Guide" document. However, the example already present in the Specification documents will need to be updated if they're found to be incorrect.

<h2 id="3.-proposed-solution-options">3. Proposed Solution Options</h2>
___

This may or may not need a change directly to the data model, but I think having a consensus regarding the interpretation and adding examples for the data structures representing each type would eliminate scope for misinterpretation. As mentioned above, the existing examples need to be reviewed for accuracy.

**Comment by ehenrka** [comment]
The given examples in the specification documents (Listing 5 in _API Definition_ and the one in _Encryption)_ are incorrect as per the defined data model and should be updated. The Swagger version is correct.

**Comment by elnyry** [comment]
Thanks Henrik.

**Comment by ehenrka** [comment]
Sam, it looks like this issue has been fixed in the version 1.1 document (I have only checked _API Definition_ as of now), should this not be in the #52 issue?

**Comment by elnyry** [comment]
hi Henrik, it is included as item #5. Thank you..

**Comment by ehenrka** [comment]
@elnyry-sam-k, the document set for v1.1 (https://github.com/mojaloop/mojaloop-specification/tree/master/fspiop-api/documents/v1.1-document-set) does not contain the _Encryption_ document v1.1. As this bug with incorrect representation for the `extensionlist` in the documents was also present in that document, it should also have been updated for v1.1. Have this been updated but not just added to the document set folder?

**Comment by elnyry-sam-k** [comment]
Thanks Henrik @ehenrka , you're right, Encryption was missing from the v1.1 doc set.

If this version looks good to you, I'll upload it (sections 1.2, 4.1, 4.1.3 have changed): 
[Encryption_v1.1.pdf](https://github.com/mojaloop/mojaloop-specification/files/6029077/Encryption_v1.1.pdf)

**Comment by ehenrka** [comment]
Thanks @elnyry-sam-k, just a tiny little styling comment.. The quotation marks around `extension` are not of the exact same style as the other quotation marks. Compare with for example the `extensionList` above. Can you please fix before upload?
![image](https://user-images.githubusercontent.com/30468528/109498408-b3c8e200-7a93-11eb-90f2-2b235a08c3a7.png)

**Comment by elnyry-sam-k** [comment]
Thanks Henrik, will fix it and upload :-)

**Comment by elnyry-sam-k** [comment]
Fixed and uploaded here: https://github.com/mojaloop/mojaloop-specification/tree/master/fspiop-api/documents/v1.1-document-set.

@ehenrka I think we can close this now

**Comment by ehenrka** [comment]
Yes, it should be fixed now in every document where it was present.
