### ISSUE TITLE
Change Request: Distributed Tracing Support for FSPIOP API

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/mojaloop-specification#71]
### **Table of Contents**

* [1. Preface](#1.-preface)
  * [1.1 Change Request Information](#1.1-change-request-information)
  * [1.2 Document Version Information](#1.2-document-version-information)
* [2. Problem Description](#2.-problem-description)
  * [2.1 Background](#2.1-background)
  * [2.2 Current Behaviour](#2.2-current-behaviour)
  * [2.3 Requested Behaviour](#2.3-requested-behaviour)
* [3 Proposed Solution Options](#3.-proposed-solution-options)

<h2 id="1.-preface">1. Preface</h2>
___

Traceability of API requests within a deployed Mojaloop implementation is paramount to the Hub Operators ability to successfully and effectively provide operational support in issue resolution. This change-request is to 

<h4 id="1.1-change-request-information">1.1 Change Request Information</h4>

| Requested By | Miguel de Barros, ModusBox |
| Change Request Status | Draft ☒ / In review ☐  / Approved ☐ / Rejected ☐ |
| Approved/Rejected Date |   |

<h4 id="1.2-document-version-information">1.2 Document Version Information</h4>

| Version | Date | Author | Change Description |
| --- | --- | --- | --- |
| 1.0 | 2020-12-10 | Miguel de Barros | Initial version. |

<h2 id="2.-problem-description">2. Problem Description</h2>
___

<h4 id="2.1-background">2.1 Background</h4>

The Mojaloop product is implemented using several distributed services, this implementation pattern being known as a micro-service architecture. A result is that a single transaction may be processed or handled by multiple services within the Mojaloop stack. This introduces a challenge for operational monitoring as it is difficult to trace or monitor a transaction as it flows through each of these distributed services.

<h4 id="2.2-current-behaviour">2.2 Current Behaviour</h4>

At present, there is a tracing solution implemented in the current Mojaloop stack as part of the [Event Framework](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/event-framework/). 

This requires several non-standard FSPIOP specification headers which contain the trace-context (ref: [Event Framework - Tracing Design - 4.1.1 W3C HTTP Headers](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/event-framework/#411-w3c-http-headers)) to be:
- processed by the Hub, and 
- forwarded by participants on call-back requests.

The result being that FSPs are not currently forwarding tracing-context headers FSPIOP call-backs. This means that traces are currently broken into each of the FSPIOP legs of the PayerFSP request and PayeeFSP call-back.

Let's take Transfers as an example:
1. Mojaloop receives a Transfer Prepare Request, assuming there is no trace-context header from the PayerFSP, a trace-context is created by Mojaloop ML-API-Adapter. This trace-context is propagated through each of the micro-services and is utilised for monitoring purposes until the notification has been sent to the PayeeFSP.
2. When receiving the Transfer Fulfil Callback from the PayeeFSP, which does not contain the forwarded trace-context headers, Mojaloop will not have the necessary context to continue the trace from the prepare-leg (i.e. point 1 above). As such a new context is created from the point of receiving the fulfilment and until the notification is sent to the PayerFSP.

Thus we end up with two distinct trace-context for each leg of the Transfer.

<h4 id="2.3-requested-behaviour">2.3 Requested Behaviour</h4>

The W3C Tracing headers as describes in following design document: [Event Framework - Tracing Design - 4.1.1 W3C HTTP Headers](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/event-framework/#411-w3c-http-headers), are included as part of the FSPIOP specification with functional information on how the Mojaloop Switch and Participants should handle or process them appropriately.

Note: Participants are not required to do any additional processing of these tracing headers, but at a minimum, they should forward the tracing headers as part of FSPIOP call-back. This will ensure that there is an unbroken transactional trace from the switch to the FSP.

Let's take Transfers as an example:
1. Mojaloop receives a Transfer Prepare Request, assuming there is no trace-context header from the PayerFSP, a trace-context is created by Mojaloop ML-API-Adapter. This trace-context is propagated through each of the micro-services and is utilised for monitoring purposes until the notification has been sent to the PayeeFSP.
2. When receiving the Transfer Fulfil Callback from the PayeeFSP, the trace-context is included as a header, Mojaloop will then process this trace-context and continue the trace from the prepare-leg (i.e. point 1 above). As such the same context is now used from the point of receiving the prepare and until the fulfilment notification is sent to the PayerFSP.

Thus we end-up with single trace-context for both legs of the Transfer.

Example demo using simulated FSPs which support the tracing standard: https://youtu.be/JGL5HfYi0wE.

<h2 id="3.-proposed-solution-options">3. Proposed Solution Options</h2>
___

Refer to the [W3C's Trace Context Level 2 Document](https://w3c.github.io/trace-context/) for more detail on the standard that is currently supported by the [Event Framework](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/event-framework).

However, there are other tracing standards that can be considered such as [Zipkin's B3 Propagation Design](https://github.com/apache/incubator-zipkin-b3-propagation).

We propose to add these as optional headers so that the changes are backwards compatible so that Schemes that implement/deploy Mojaloop can decide on their usage (making them mandatory or optional for their Scheme).

**Comment by jmssebunnya** [comment]
Aligned to the need for the trace header to the added.

>

**Comment by ehenrka** [comment]
Thank you @mdebarros.

I'm OK with adding the W3C trace headers to the FSPIOP API as optional headers, making these the _recommended_ way of adding traces. I don't want to make them mandatory to implement as would be the implication of the following part:

> Participants are not required to do any additional processing of these tracing headers, but at a minimum, they should forward the tracing headers as part of FSPIOP call-back. This will ensure that there is an unbroken transactional trace from the switch to the FSP.

The FSPIOP API is a generic standard which could be used in a scheme where another Switch than the Mojaloop switch is used, or in a bilateral setup without a Switch, which is why I do not want these headers to be mandatory in the API. It should rather be the scheme rules that decides that these trace headers must be used within the scheme. Some schemes might choose to use other tracing mechanisms, or none at all. There should not be a requirement on implementers of the API to support them if they will not be used within a scheme as they are in no way required for the API to work.

Kind regards,
Henrik

**Comment by jmssebunnya** [comment]
Seconded. @Henrik
Trace headers to be added but not mandatory .
Scheme rules can decide on the obligation to mandate  its participants to
include them.

Best Regards
Mark

**Comment by elnyry-sam-k** [comment]
Thanks @ehenrka , @jmssebunnya - agree with you; the goal is to add these to the Spec as **optional** and let Schemes decide on whether to make them required for that Scheme or not

**Comment by ehenrka** [comment]
@mdebarros and @elnyry-sam-k, as there have been no more comments regarding the change request, can you please go ahead and make a solution proposal containing the actual changes to the specification?

**Comment by elnyry-sam-k** [comment]
Thanks @ehenrka , sure

**Comment by ehenrka** [comment]
I have proposed in the last SIG meetings to add the optional HTTP headers for tracing support to the existing version 1.1 of the API. This suggestion is related to my approved suggestion back in 2019 (email subject _Open API for FSPIOP: Versioning of document and resources_), where we decided to separate the document version and versions for different resources in the API.

As the tracing HTTP headers (`traceparent`, `tracestate`) are optional and does not need to be handled if they are received by an FSP, we should be able to safely add them to a new patch document version (1.1.1) of the API Definition document without any impact for existing implementations. There will be no changes to any of the resources of the API.

The suggestion then is to:
- Create a new table in Section 3.2.1.1 (HTTP Request Header Fields) to describe optional HTTP header fields, as the current Table 1 only describes HTTP headers that must be implemented.
- Add tracing HTTP headers (`traceparent`, `tracestate`) to the new table for optional HTTP headers and add reference to the _Distributed Tracing Support for OpenAPI Interoperability_ document for detailed information.
- Update document version to new patch version 1.1.1, describe changes in Section 1.2

**Comment by elnyry-sam-k** [comment]
Thanks Henrik (@ehenrka ) for the recommendations. We should be able to implement these and conclude this issue

**Comment by ehenrka** [comment]
Please review #95, which contains the changes described in https://github.com/mojaloop/mojaloop-specification/issues/71#issuecomment-876946837.

**Comment by henrka** [comment]
Closing as supported since version 1.1.1
